name: Helium
version: $version
main: dev.kamiql.helium.Main
api-version: 1.21

folia-supported: true

libraries:
  - "org.jetbrains.kotlin:kotlin-stdlib:2.3.20"
  - "io.github.revxrsal:lamp.bukkit:4.0.0-rc.16"
  - "io.github.revxrsal:lamp.common:4.0.0-rc.16"
  - "com.fasterxml.jackson.core:jackson-databind:2.21.3"
  - "com.fasterxml.jackson.module:jackson-module-kotlin:2.21.3"
  - "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.21.3"
  - "com.fasterxml.jackson.dataformat:jackson-dataformat-toml:2.21.3"